### ISSUE TITLE
Potential preview issues

### ISSUE THREAD

**Issue by MariuszDabrowski** [nuxt-community/prismic-module#132] opened 2021-04-01 13:49 UTC
We recently did a `Bump @nuxtjs/prismic from 1.2.4 to 1.2.6` on our project and noticed Prismic previews stopped working. No other code on the project changed.

We reverted this bump and sure enough the previews started working again, any ideas as to what might be happening here?

Some additional details:
- We're previewing on localhost
- All previews broke
- Followed the troubleshooting guide here: https://user-guides.prismic.io/en/articles/3403530-troubleshooting-previews

**Comment by lihbr** [comment] 2021-04-01 13:58
Hey @MariuszDabrowski, thank you so much for letting us know!

Can you share your version of Nuxt & Node also? Thanks!

**Comment by MariuszDabrowski** [comment] 2021-04-01 16:14
`"nuxt": "^2.15.3"`
`"node": "14.15.1"`

**Comment by lihbr** [comment] 2021-04-01 16:51
Thanks! I'll investigate that next week, in the meantime for your intention here are the two change we introduced since `1.2.4`:
- https://github.com/nuxt-community/prismic-module/commit/5e443508e1c69540f63a512675ce5a35ab428df8#diff-0702cfb7026ef4a87ca46003aa83c63e6a33be6a91edf840e50b77f0b6c2e73d
- https://github.com/nuxt-community/prismic-module/commit/6f60b21d596306585391ffde7a662b1a87fdbf11#diff-0702cfb7026ef4a87ca46003aa83c63e6a33be6a91edf840e50b77f0b6c2e73d

**Comment by lihbr** [comment] 2021-04-19 15:33
Hey,

I took some time today to reproduce the issue on a simple project using `nuxt@2.15.4` with `@nuxtjs/prismic@1.2.6` and `node@14.15.3`.  Unfortunately, I didn't manage to reproduce the issue on both a local server (`nuxt`) and a production build (`nuxt generate` over Netlify).

I'll close this issue for now. Please reopen it if you're still experiencing it, I'd be happy to dig into it further if you can share your complete `package.json` and `nuxt.config.js` file along your Prismic repository name. A minimal reproduction would also greatly help.

If anyone's experiencing the issue Marius raised here please also notify me so I can prioritize that one 🙂

**Closed by lihbr** 2021-04-19 15:33 UTC
Labels: bug, help wanted
