### ISSUE TITLE
Layouts Preview does not work when building in full static mode

### ISSUE THREAD

**Issue by yannbertrand** [nuxt-community/prismic-module#154] opened 2021-11-24 13:54 UTC
### Versions

- nuxt: 2.15.7
- @nuxtjs/prismic: 1.3.2
- node: 16.10.0

### Reproduction

**Reproduction repository** : 
https://github.com/yannbertrand/prismic-nuxt-preview-test

**Built app with a beta header** : ✅ works after static build
https://prismic.link/3cLAI4o

<details>
<summary>Screenshots</summary>
Prismic config
<img src="https://user-images.githubusercontent.com/5855339/143224059-f29ab1a4-756b-44ec-a219-8fb03de9f215.png">

Result
<img src="https://user-images.githubusercontent.com/5855339/143246066-e1463bfe-e426-4660-8e0b-eb10fb32c839.png">
</details>

---

**Dev app with a beta footer** :  ✅ works before static build
<details>
<summary>Screenshots</summary>
#### Prismic config
<img src="https://user-images.githubusercontent.com/5855339/143224117-c5596526-184a-4762-8ff5-4a5079a16623.png">

#### Result
<img src="https://user-images.githubusercontent.com/5855339/143245937-3d1ada06-2beb-4f98-8d37-96dbfa1940d0.png">
</details>

---

**Built app with a beta footer** : ❌ does not work after static build
https://prismic.link/3cLCwud 

<details>
<summary>Screenshots</summary>
#### Prismic config
<img src="https://user-images.githubusercontent.com/5855339/143224117-c5596526-184a-4762-8ff5-4a5079a16623.png">

#### Result
<img src="https://user-images.githubusercontent.com/5855339/143224153-ea7e31ba-2c6b-4cc4-b7e2-027c1438a4d4.png">
</details>

### Steps to reproduce
1. Clone the [repository](https://github.com/yannbertrand/prismic-nuxt-preview-test)
1. Install deps `npm install`
1. Change the `PRISMIC_APIS_HREF` value in `nuxt.config.js` to one you created (*see next section "Prismic config")
1. Launch the project with `npm run dev`
1. Activate Prismic preview mode on the local env for the `main_footer`
1. See that it is really previewed on the footer layout element
1. Stop the dev server
1. Build the project using `npm run build`
1. Launch the statically build project server locally `npm run start`
1. See that the preview does not work on the footer layout element

#### Prismic config
Here is the Prismic setup I used (but you should be able to tweak it and reproduce the issue):
- Custom Type - `slices_page` with a `URI` uid field and both `banner_title` + `banner_content` RTE fields
- Custom Type - `main_footer` with a `footer_for`select field (with `pix-site` default value) and a `text` RTE paragraph field
- A published `fr-fr` Slices page with the URI `index-pix-site` with a running modification (ready to be previewed)
- A published `fr-fr` Main footer with the `footer_for=pix-site` with a running modification (ready to be previewed)

### What is Expected?
Preview mode should work the same way in Developpement+SSR+Static and after Full Static build.

### What is actually happening?
Preview mode works the same way on page elements, but not on layout instantiated component.

**Comment by lihbr** [comment] 2021-11-24 17:14
Hey there, thank you so much for the detailled report! I'll have a look at it next week.

At first glance it looks like this is probably related to the following: https://github.com/nuxt/nuxt.js/issues/9439

I'll investigate that!

**Comment by yannbertrand** [comment] 2021-11-24 21:48
Thank you for your help! Let me know if you need more information :)

**Comment by lihbr** [comment] 2021-11-29 10:55
Hey there,

Thanks to your detailed instruction I was able to reproduce easily the behavior you encountered.

So the issue here is the one described in this Nuxt issue: https://github.com/nuxt/nuxt.js/issues/9439 (the one from before), but tl;dr; Nuxt is not able to refresh `fetch` hooks coming directly from a layout file (not a page).

I'll try to push for the PR fixing that to be merged. In the meantime, I'd recommend setting layouts data through the store rather than with the `fetch` hook, You can also stay like that, assuming that it's fine for you to not have previews working with layouts (while it might be more critical for blog posts for example)

**Comment by yannbertrand** [comment] 2021-11-30 10:29
Thank you for the update and providing a temporary patch! We'll definitely look into using the store to get data.

Is it ok to keep this issue open until the PR you mention is merged? It would be the best for us to get updated :)

**Comment by lihbr** [comment] 2021-11-30 12:15
Definitely ☺️ This is still a valid "bug"

**Comment by lihbr** [comment] 2022-03-16 10:11
Sadly the PR fixing this one on Nuxt end (https://github.com/nuxt/nuxt.js/pull/9530) won't land as Nuxt team shifts its effort toward Nuxt 3.

I'm closing it with a `wontfix` flag and will update it should the PR change its status.

**Closed by lihbr** 2022-03-16 10:11 UTC
Labels: bug, wontfix
