### ISSUE TITLE
If Prismic endpoint is not available then complete website is down

### ISSUE THREAD

**Issue by jainsuneet** [nuxt-community/prismic-module#77] opened 2020-05-22 15:46 UTC
As per the documents I am injecting Prismic in the modules section of the nuxt.config.js.

```
modules: ['@nuxtjs/prismic' ],
prismic: {
    endpoint: 'https://your-repo-name.cdn.prismic.io/api/v2',
    linkResolver: '@/plugins/link-resolver',
    htmlSerializer: '@/plugins/html-serializer'
}
```

I am integrating prismic content as blog in my existing nuxt website at /blogs, I realized that if in case Prismic URL is not available (if Prismic server is down or URL is incorrect) then the complete website doesn't load at all (all routes are blocked).

Can you please suggest any workaround for this ?

**Comment by lihbr** [comment] 2020-05-23 10:57
I think that's due to the plugin trying to get the API on injection ([here](https://github.com/nuxt-community/prismic-module/blob/master/src/templates/plugins/prismic.js#L17)). Perhaps it should just fail silently (loggin error but not throwing) or init the API not on load but only when requested 🤔

**Comment by suneetjain** [comment] 2020-05-23 11:07
> I think that's due to the plugin trying to get the API on injection ([here](https://github.com/nuxt-community/prismic-module/blob/master/src/templates/plugins/prismic.js#L17)). Perhaps it should just fail silently (loggin error but not throwing) or init the API not on load but only when requested

I am only including the plugin in modules of nuxt config and my app is universal. Not all the pages are using this plugin, only one page called /blog. Even the root of the website is blocked when there is no prismic related calls in index file.

**Comment by hypervillain** [comment] 2020-06-01 09:26
If it doesn't come from the instantiation of the api then I'm not sure I understand the issue. What does your blog page looks like? When you mention incorrect urls, do you mean that you try to query a non-existing document on Prismic? Also, does it happen on both dev and production?

I'll try to reproduce on my side!

**Comment by suneetjain** [comment] 2020-06-02 06:42
> If it doesn't come from the instantiation of the api then I'm not sure I understand the issue. What does your blog page looks like? When you mention incorrect urls, do you mean that you try to query a non-existing document on Prismic? Also, does it happen on both dev and production?
> 
> I'll try to reproduce on my side!

I just include it in nuxt.config file like I mentioned in my original question ... the blog page is not initialized so there is yet no query. An incorrect link in the nuxt.config blocks the complete application.

**Comment by hypervillain** [comment] 2020-06-03 13:28
That's right, the js kit throws a 404 when used an invalid API endpoint. 
Which is fine I believe, as not providing an endpoint simply defeats the purpose of such module. In your case, removing the module declaration until you need it seems preferable 👍

Let me know if you have another opinion on the matter ofc

**Comment by suneetjain** [comment] 2020-06-03 13:31
> That's right, the js kit throws a 404 when used an invalid API endpoint.
> Which is fine I believe, as not providing an endpoint simply defeats the purpose of such module. In your case, removing the module declaration until you need it seems preferable 👍
> 
> Let me know if you have another opinion on the matter ofc

The root of Nuxt app is not calling the API but only /blogs is calling. For Nuxt it is injected in modules and the complete app is blocked. If an error is thrown then the app should load but this is not the case.

**Comment by hypervillain** [comment] 2020-06-03 14:09
The root of your app may not call the API but the module does when it injects prismic in your project.

The problem I can see with the module breaking here is if your app server-renders  content and the endpoint somewhat becomes unavailable.

But as of today, if your website breaks because you don't provide the module with a valid endpoint, then you could simply not declare the module in the first place (until you input some content in your writing room)!

**Comment by suneetjain** [comment] 2020-06-03 14:13
> The root of your app may not call the API but the module does when it injects prismic in your project.
> 
> The problem I can see with the module breaking here is if your app server-renders content and the endpoint somewhat becomes unavailable. And in other cases, you actually don't want your website to be rebuilt.
> 
> But as of today, if your website breaks because you don't provide the module with a valid endpoint, then you could simply not declare the module in the first place (until you input some content in your writing room)!

An app cannot be exclusive for one module. There is no problem with the module loading but the error handling mechanism of this module. The bug should be resolved with this module otherwise all the Nuxt apps using this module will go down if the Prismic server is down.

**Comment by hypervillain** [comment] 2020-06-03 14:46
Ok I'll leave open and see what I can do

**Comment by lihbr** [comment] 2020-07-17 14:01
Closed in #85

**Closed by lihbr** 2020-07-17 14:01 UTC

**Comment by mmanousou** [comment] 2020-10-09 13:32
@lihbr @hypervillain we've had our website go down twice this week even though I can see in our logs it says "Preventing fatal error". So seems like it's not actually preventing the error. 

We're investigating our Prismic content to see if there's something broken on that side but thought I would comment on this issue as well. 

@jainsuneet is this working fine for you after this fix?

**Comment by lihbr** [comment] 2020-10-09 14:31
Hey @mmanousou, I'm sorry to hear that your website went down this week, [we indeed had a minor outage for some customers on Tuesday](https://status.prismic.io/history).

In such cases, the `trycatch` statement we added should only prevent pages not relying on Prismic at all to fail (@jainsuneet use case). I retested to be sure, HTTP and URL errors caused by the module on those do not lead to a fatal as expected. If you want to prevent pages using Prismic from leading to fatal I guess you can wrap calls to Prismic inside `trycatch` statements, just like if you were querying a standard API.

I'm curious if you can share your Nuxt config file and module version to help us troubleshoot that further if you want ☺️

**Comment by mmanousou** [comment] 2020-10-09 14:53
hey @lihbr thanks so much for getting back to me so quickly! I didn't try to access a non-prismic page at the time unfortunately. We always use try/catch for our Prismic calls but will have another look into it :/ 

We use nuxt 2.14.6 and @nuxtjs/prismic 1.2.4. Here's part of our nuxt config if it helps. Please let me know if i can provide more info.
 
```
buildModules: [
    '@nuxtjs/prismic'
  ],
prismic: {
    endpoint: process.env.CONTENT_URL,
    linkResolver: '@/plugins/link-resolver.js',
    htmlSerializer: '@/plugins/html-serializer.js',
    preview: '/preview'
  },`

**Comment by lihbr** [comment] 2020-10-09 15:09
You're welcome! Config looks good to me, I guess you're using Nuxt SSR with Node right? (according to your modules) Not sure of what could cause it so far as long as your `CONTENT_URL` environment variable is filled correctly.

Happy to dig more into it if you figure out how to reproduce a fatal with a `trycatch` statement ☺️

**Comment by jainsuneet** [comment] 2020-10-14 07:45
> @lihbr @hypervillain we've had our website go down twice this week even though I can see in our logs it says "Preventing fatal error". So seems like it's not actually preventing the error.
> 
> We're investigating our Prismic content to see if there's something broken on that side but thought I would comment on this issue as well.
> 
> @jainsuneet is this working fine for you after this fix?

There is still no proper solution, because of that we decided to move to another cms solution (Strapi). We cannot allow one module to break the whole website.

This is a worst case scenario but as @lihbr mentioned that they had an outage and any sort of outage on Prismic is directly impacting the website using it completely, even you are using Prismic only on your certain pages of website.

**Comment by gabrielsze** [comment] 2021-04-03 03:04
This seems to be a rather serious issue and quite a determiner in what cms we go with, wanted to ask if there are any updates on this...
